In [ ]:
from google.colab import files
uploaded = files.upload()

Saving IRIS.csv to IRIS (2).csv

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import gradio as gr
df =pd.read_csv("IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
X=df.drop("species", axis=1)
y=df["species"]

y = y.astype("category").cat.codes

In [ ]:
#train -test and split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#train the model using LogisticRegression
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [ ]:
#step 6- define the predictions func
def predict_iris(sepal_length, sepal_width, petal_legth, petal_width):
    input_data = np.array([[sepal_length, sepal_width, petal_legth, petal_width]])
    prediction = model.predict(input_data)[0]
    species_name = df["species"].astype("category").cat.categories[prediction]
    return f" predict species: {species_name}"

In [ ]:
#step7 gradio ap
iface = gr.Interface(
   fn = predict_iris,
   inputs=[
     gr.Slider(4.0, 8.0, step=0.1, label = "sepal Length (cm)"),
     gr.Slider(2.0, 5.0, step=0.1, label = "sepal width (cm)"),
     gr.Slider(1.0, 7.0, step=0.1, label = "petal Length (cm)"),
     gr.Slider(0.1, 2.5, step=0.1, label = "petal width (cm)")
   ],
   outputs = gr.Textbox(label = "prediction"),
   title = "project 1: smart iris flower classifier using logistic regression and gradio deployment"
)

In [ ]:
iface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://a34f8580c04e503ab2.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)